cmeutils/gsd_utils.py
cmeutils/tests/base_test.py
cmeutils/tests/test_gsd.py

This PR does the following:
- **Allows all of the functions in `gsd_utils.py` to handle either a gsd file and frame number, or work directly with a `gsd.hoomd.snapshot`**
I added a `_validate_inputs()` function which both checks for what is being passed in (file or snap) and does some quick validation. The function returns a `snapshot` regardless of what's passed in. It gets called at the beginning of each of the util functions, which then work with snapshots.
- **Re-names a couple functions**
`frame_get_type_positions` renamed to `get_type_positions` so that it's shorter.
`snap_molecule_indices` renamed to `snap_molecule_cluster` so that it more closely  matches the naming of `freud.cluster.Cluster()` which this function is basically a quick wrapper for. 
- **Adds a new function that …

Standardize file type handling in gsd_utils

---

cmeutils/__init__.py
cmeutils/structure.py
cmeutils/tests/test_structure.py
environment.yml

The `compute` method for rhe `freud.diffraction.Diffractomer` class takes a quaternion as the [view_orientation kwarg](https://freud.readthedocs.io/en/latest/modules/diffraction.html#freud.diffraction.DiffractionPattern.compute). In order to use this module the same way the old diffractometer code was used, we need to convert the rotation matrices to quaternions.
- ~`rotmat_to_q` calculation follows [this example](http://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToQuaternion/).~
- `get_quaternions` uses similar logic to get the view vectors as `prep_matrices` from bitbucket `cme_utils/analyze/diffractometer.py` 
- ~`rotation_matrix_from_to` is from bitbucket `cme_utils/manip/utilities.py` (only docstring formatting has been updated.)~
- Bradley Dice in the glotzer …

Add utilities so that `freud.diffraction.Diffractometer` can be used like bitbucket diffractometer code

---

cmeutils/__init__.py
cmeutils/dynamics.py
cmeutils/gsd_utils.py
cmeutils/structure.py
cmeutils/tests/base_test.py
cmeutils/tests/test_dynamics.py
cmeutils/tests/test_gsd.py
cmeutils/tests/test_structure.py

This PR puts the MSD from GSD functionality that we have floating around in various notebooks and python files into a single location.  
Also, I updated `get_type_position` to accept a list (or iterable) of atom types and return their positions as opposed to only accepting a single atom type.  I think this will offer more flexibility.
Still needs unit tests and doc strings, but I figured I'd put it up here for others to comment on.

Create dynamics.py with Freud MSD functionality

---

cmeutils/gsd_utils.py

As suggested by Jenny in PR #24, I replayed the changes in commit 2701ce4 onto the current master branch with git cherry-pick as seen below:
```
git checkout master 
git pull upstream master
git checkout -b value-error-2
git cherry-pick 2701ce4
```
Hoping this will be a way of getting around some issues I was facing with the other pull request

changed value error output in attempt to fix issue #14.

---

cmeutils/structure.py
cmeutils/tests/test_structure.py

This PR creates 2 functions. One that returns the bond lengths for a given bond pair, and one that returns bond angles for a given angle triplet.  It allows the user to accumulate lengths and angles over a range of snapshots for better sampling.
A quick note about handling PBCs: I chose to use the periodic images stored in the gsd file to unwrap positions before finding the bond vectors. I think the other option would be to check if a vector is larger than half the box and correct it using the box length, but I'm not sure how to do that if we don't have a cubic volume. IMO, unwrapping the relevant positions first seems like the best option.

Bond length and angle distributions

---

.gitignore
cmeutils/structure.py
cmeutils/tests/test_structure.py

This addresses #28 and fixes the RDF normalization errors that result when types A and B are different, and there are different amount of each type.
I'm leaving this as a WIP, as I don't think we are totally sure of the origin of the issue and might want to discuss it more, but this does fix the normalization issues. In other words, the RDFs returned are the same regardless of what order types A and B are passed into `gsd_rdf` when there are different amounts of A/B types in the system..

Fix RDF normalization when type A and B are different

---

cmeutils/plotting.py
cmeutils/structure.py
cmeutils/tests/test_plotting.py
cmeutils/tests/test_structure.py

Both of the `angle_distribution` and `bond_distribution` functions are a bit of a misnomer.  Currently, they only return an array of the calculated bond angles and lengths, rather than giving the actual distributions.
This PR adds an additional parameter to these functions that returns a distribution of these values. I decided to add a parameter rather than outright changing the behavior of the function in case there are still use cases where we want a list of the actual bond lengths and angles. However, I'm open to changing this if someone thinks there is a better approach.
I still need to add some unit tests.

Add get_histogram utility, option to return histogram of bond lengths and angles

---

cmeutils/plotting.py
cmeutils/tests/test_plotting.py

This function computes a nice 3d color-coded scatter plot from three lists of numbers.

Chris suggested this PR for plotting this 3d heat map type plot.

---

.github/workflows/pytest.yml
cmeutils/gsd_utils.py
cmeutils/tests/test_gsd.py
environment.yml

Having hoomd2 as a dependency creates a problem when trying to use cmeutils in an environment that also has hoomd 3.  Since we only need hoomd for the `xml_to_gsd` function, I moved the hoomd imports inside of that function and throw an error if the user needs to add hoomd 2 to their environment.

remove hoomd 2 from environment file

---

cmeutils/geometry.py
cmeutils/tests/test_geometry.py

This is useful for rigid body stuff, so I figured we could add it to our "tool box".
I still need to make a unit test for it. Just making the PR now to get another set of eyes on it.
Also, credit to Jenny for writing the function, I just copied it over to this repo.

Add moment of inertia function

---

cmeutils/structure.py
cmeutils/tests/test_structure.py

It looks like the normalization parameter in both bond and angle distribution functions wasn't doing anything. The actual normalization is performed in `plotting.get_histogram`, which both of these functions use, but the normalization parameter was never passed along.  This PR fixes that, and adds 2 unit tests that call the bond and angle distribution functions (the normalization was already tested directly by calling `get_histogram`)

Fix normalizaiton of bond and angle distributions

---

.github/workflows/pytest.yml
cmeutils/gsd_utils.py
cmeutils/sampling.py
cmeutils/tests/test_gsd.py
environment.yml

There were some breaking changes from pymbar 3 to 4, but for the purposes of what we use in cmeutils, it only requires changing some function names.  This PR should fix those, and changes the version to >= in the environment file.

Update to pymbar Version 4

---

cmeutils/dynamics.py
cmeutils/geometry.py
cmeutils/gsd_utils.py
cmeutils/plotting.py
cmeutils/sampling.py
cmeutils/structure.py
cmeutils/tests/test_geometry.py
environment.yml

This PR adds the following functions to the geometry file:
1) `radial_grid_positions`: returns a radial grid of 2D positions between two radii.  Number of circles between the two radii, number of points in each circle and the coverage angle of each circle can be customized.
2) `spherical_grid_positions`: returns a spherical grid of 3D positions between two radii and an angle along z axis. Number of circles between the two radii, number of points in each circle and the coverage angle of each circle can be customized.
These functions can be useful when a fixed set of positions needs to be swipped in a simulation.

Add 2D and 3D grid positions

---

.github/workflows/build.yml
.github/workflows/pytest.yml
.gitignore
.pre-commit-config.yaml
cmeutils/dynamics.py
cmeutils/geometry.py
cmeutils/gsd_utils.py
cmeutils/plotting.py
cmeutils/sampling.py
cmeutils/structure.py
cmeutils/tests/base_test.py
cmeutils/tests/test_dynamics.py
cmeutils/tests/test_geometry.py
cmeutils/tests/test_gsd.py
cmeutils/tests/test_imports.py
cmeutils/tests/test_plotting.py
cmeutils/tests/test_sampling.py
cmeutils/tests/test_structure.py
codecov.yml
environment-dev.yml
setup.py

This PR add pre-commit hooks to the repository, which helps with keeping the code clean and avoids formatting confusions.
I added the following hooks which are pretty common:
- `pre-commit-hooks`
- `check-yaml`: checks yaml files for parseable syntax.
- `end-of-file-fixer`: ensures that a file is either empty, or ends with one newline.
- `trailing-whitespace`: trims trailing whitespace.
- Line length is set to 80 for all files.
- `isort`: sorts imports alphabetically and automatically separates into sections and by type. 
- `flake8`: for style guide enforcement.
-  note: flake8 errors can be annoying sometimes, but I think it's better to keep it as it makes the code cleaner.
- When necessary, we can easily [ignore flake8 errors ](https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html) …

Setting up pre-commit hooks

---

cmeutils/__init__.py
cmeutils/tests/base_test.py
cmeutils/tests/test_visualize.py
cmeutils/visualize.py
environment-dev.yml
environment.yml

This works as is right now, but is still a WIP, and open to feedback!
This is really just a wrapper for Fresnel that is designed around loading a GSD file, and visualizing different frames. All of the fresnel objects are automatically set up, and there are setters for just about all of the parameters for these objects making it easy to change something and view it.

Fresnel wrapper class to quickly and easily view GSD files in Notebooks

---

cmeutils/tests/test_visualize.py
cmeutils/visualize.py

This PR adds the simulation box to the rendered images.

Add box to fresnel visualization

---

cmeutils/tests/test_visualize.py
cmeutils/visualize.py

This adds a hidden attribute that scales the default height which is calculated from the box. This just serves as a buffer to make sure we are visualizing the entire simulation volume. This is not used when the height attribute is set explicitly.

Add a height scaling factor when using default height

---

cmeutils/tests/test_visualize.py
cmeutils/visualize.py

The camera position was slightly skewed because I was subtracting 0.5 from all coordinates. This PR changes this to use a multiplication factor to slightly adjust the camera position outward.

Fix camera position buffer factor

---

cmeutils/tests/test_visualize.py
cmeutils/visualize.py

This PR adds a way to manually set colors besides using a dictionary with particle_type:color pairings.  For example, to set different colors for the first half and second half of particles by count:
Here is a quick example. It's from the welding tutorial in hoomd_organics:
```
sim_viewer = FresnelGSD(gsd_file="tensile.gsd", view_axis=(0, 1, 0), frame=-1, height=16)
weld_colors = np.zeros_like(sim_viewer.positions)
weld_colors[:weld_colors.shape[0]//2 + 1] = np.array([0.5, 0.25, 0.5])
weld_colors[weld_colors.shape[0]//2 + 1:] = np.array([0.5, 0.1, 0.1])
sim_viewer.colors = weld_colors
```

Add setter for colors property

---

cmeutils/gsd_utils.py
cmeutils/structure.py
cmeutils/tests/test_gsd.py
cmeutils/tests/test_structure.py

This PR adds a function that acts as a wrapper for freud's [1D structure factor objects](https://freud.readthedocs.io/en/latest/modules/diffraction.html). It basically follows the same structure/format as the `gsd_rdf` function.

Add structure factor wrapper

---

cmeutils/gsd_utils.py
environment-dev.yml
environment.yml

This PR updates the environment yaml files to use hoomd >= 4.0 so that it is compatible with `flowermd` when installing from conda. Because of this, a couple properties were removed from setting up rigid bodies (charges and diameter).

update to hoomd4, fix rigid body stuff

---

cmeutils/geometry.py
cmeutils/tests/test_geometry.py

This PR adds a method to `cmeutils.geometry` which finds the best fit vector through a set of 3D coordinates. The idea here (for initially straight polymer chains at least), this vector represents the "backbone" of the chain. This is useful for performing translations on polymers built using the polymer builder in mbuild or loaded from SMILES. Usually, these compounds don't have a simple initial alignment. If we know the backbone vector, then we can use the mbuild coordinate transformation methods on the whole chain.

Add method  to `Geometry` which finds best fit vetctor through a set of coordinates.

---

cmeutils/geometry.py
cmeutils/tests/test_geometry.py

I made a last second change that returned the absolute value of the vector, but that broke the expected behavior in `flowermd`. I don't think it is really necessary to return the absolute value.

Fix error in `get_backbone_vector`

---

cmeutils/plotting.py
cmeutils/tests/test_plotting.py
cmeutils/tests/test_structure.py

This PR fixes how we normalize the histogram heights returned by numpy.histogram.

Fix histogram normalization

---

cmeutils/gsd_utils.py

This is a small change that moves the hoomd import from the top of `gsd_utils.py` into the `create_rigid_snapshot` method, which is the only place it is used. 
Importing and using other cmeutils methods was causing issues on clusters when my environment had the gpu-version of hoomd, but the job wasn't on a gpu node.

Move hoomd import inside rigid body function

---

environment-dev.yml
environment.yml

Related to #81. We can pin to 2.13.2 until we fix the breaking changes. [A PR to the feedstock](https://github.com/conda-forge/cmeutils-feedstock/pull/14l) is open which pins the version on conda-forge as well.

Pin freud to v2.13.2 in environment files.

---

cmeutils/structure.py
cmeutils/tests/base_test.py
cmeutils/tests/test_structure.py

This PR adds a new function to `structure.py` which plots the concentration profile of left particles and right particles which is useful for measuring diffusion across an interface in the case of polymer welding.

Add concentration profile function for plotting diffusion across an interface

---

cmeutils/sampling.py
cmeutils/tests/test_gsd.py
cmeutils/tests/test_sampling.py
environment-dev.yml
environment.yml

I just added the autocorrelation function to sampling.py.

Adding autocorrelation function to sampling.py.

---

cmeutils/gsd_utils.py

As per https://hoomd-blue.readthedocs.io/en/v5.3.0/hoomd/md/pair/aniso/gayberne.html, "The parallel direction is aligned with z axis in the particle’s reference frame." Also, according to https://gsd.readthedocs.io/en/v4.0.0/shapes.html#ellipsoids, the `c` parameter is the radius in the z direction, so the current behavior displays ellipsoids rotated from where they should be.

correct ellipsoid axes in gsd visualization function

---

.github/workflows/pytest.yml
.pre-commit-config.yaml
environment-dev.yml
environment.yml

This PR adds python 3.13 to the environment files and the CI testing, and pins numpy to >=2.0. This also pins freud to the latest released version after [finding a bug in their MSD module](https://github.com/glotzerlab/freud/issues/1342). This fixes #104

Pin numpy >= 2.0, add python 3.13 to testing, pin freud to avoid MSD bug
